name: lint

on:
  workflow_call:
    inputs:
      langchain-location:
        required: false
        type: string
        description: "Relative path to the langchain library folder"

env:
  WORKDIR: "."

  # This env var allows us to get inline annotations when ruff has complaints.
  RUFF_OUTPUT_FORMAT: github

jobs:
  build:
    name: "make lint #${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Only lint on the min and max supported Python versions.
        # It's extremely unlikely that there's a lint issue on any version in between
        # that doesn't show up on the min or max versions.
        #
        # GitHub rate-limits how many jobs can be running at any one time.
        # Starting new jobs is also relatively slow,
        # so linting on fewer versions makes CI faster.
        python-version:
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }} + uv
        uses: "./.github/actions/setup"
        with:
          python-version: ${{ matrix.python-version }}
          cache-key: lint-with-extras

      - name: Check uv lock file
        shell: bash
        run: |
          uv lock --check

      - name: Install dependencies
        # Also installs dev/lint/test/typing dependencies, to ensure we have
        # type hints for as many of our libraries as possible.
        #
        # If you change this configuration, make sure to change the `cache-key`
        # in the `setup` action above to stop using the old cache.
        # It doesn't matter how you change it, any change will cause a cache-bust.
        run: |
          uv sync --group lint --group typing

      - name: Install langchain editable
        if: ${{ inputs.langchain-location }}
        env:
          LANGCHAIN_LOCATION: ${{ inputs.langchain-location }}
        run: |
          uv pip install -e "$LANGCHAIN_LOCATION"

      - name: Get .mypy_cache to speed up mypy
        uses: actions/cache@v4
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MIN: "2"
        with:
          path: |
            ${{ env.WORKDIR }}/.mypy_cache
          key: mypy-lint-${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}-${{ hashFiles('uv.lock') }}

      - name: Install unit test dependencies
        # Also installs dev/lint/test/typing dependencies, to ensure we have
        # type hints for as many of our libraries as possible.
        #
        # If you change this configuration, make sure to change the `cache-key`
        # in the `setup` action above to stop using the old cache.
        # It doesn't matter how you change it, any change will cause a cache-bust.
        run: |
          uv sync --group test

      - name: Analysing the code with our lint
        run: |
          make lint_package

      - name: Install unit+integration test dependencies
        run: |
          uv sync --group test --group test_integration

      - name: Get .mypy_cache_test to speed up mypy
        uses: actions/cache@v4
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MIN: "2"
        with:
          path: |
            ${{ env.WORKDIR }}/.mypy_cache_test
          key: mypy-test-${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}-${{ hashFiles('uv.lock') }}

      - name: Analysing the code with our lint
        run: |
          make lint_tests
