name: Scheduled tests
run-name: langchain-llama-stack Scheduled tests

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python + uv
        uses: "./.github/actions/setup"
        with:
          python-version: ${{ matrix.python-version }}
          cache-key: scheduled

      - name: Install dependencies
        run: uv sync --group test --group test_integration

      - name: Run unit tests
        run: make tests

      - name: Run integration tests
        env:
          LLAMA_STACK_API_KEY: ${{ secrets.LLAMA_STACK_API_KEY }}
          LLAMA_STACK_BASE_URL: ${{ secrets.LLAMA_STACK_BASE_URL }}
        run: make integration_tests

      - name: Ensure the tests did not create any additional files
        run: |
          set -eu

          STATUS="$(git status)"
          echo "$STATUS"

          # grep will exit non-zero if the target message isn't found,
          # and `set -e` above will cause the step to fail.
          echo "$STATUS" | grep 'nothing to commit, working tree clean'
